package com.learnease.server.model.enums;

public enum BookingErrorCode {

    USER_NOT_FOUND,
    STUDENT_PROFILE_NOT_FOUND,
    USER_NOT_ACTIVE,
    USER_NOT_STUDENT,

    COURSE_NOT_FOUND,
    INSTRUCTOR_NOT_FOUND,
    INSTRUCTOR_NOT_ALLOWED,

    BOOKING_ALREADY_PAID,
    BOOKING_EXPIRED,
    BOOKING_NOT_FOUND,
    INVALID_BOOKING_STATE,
    ORDER_ID_MISMATCH,
    INVALID_PAYMENT_SIGNATURE,
    PAYMENT_REJECTED,
    PAYMENT_ORDER_CREATION_FAILED,
    PAYMENT_VERIFICATION_FAILED
}
